### ISSUE TITLE
需要告知用户SAFE MAX是什么，添加提示信息

### ISSUE THREAD

**Issue by WuEthereum** [Lendfme/front_end_mc#24]
![image](https://user-images.githubusercontent.com/32732224/70200087-635abb80-174e-11ea-8896-08f9d3e94f65.png)

**Comment by LENDFORME** [comment]
中文：先抵押再借款
EN: Please supply assets as collaterals first.

**Comment by LENDFORME** [comment]
在输入框的右侧加一个叹号，鼠标悬浮时提示：
中文：抵押率低于125%时，抵押物将被清算，SAFE MAX允许你的借款量保持健康的抵押率
EN: When the collateral ratio is lower than 125%, your under-collateralized assets would be liquidated, SAFE MAX allows you to keep a much healthy collateral ratio.
