### ISSUE TITLE
添加谷歌追踪码

### ISSUE THREAD

**Issue by WuEthereum** [Lendfme/front_end_mc#33]
google追踪码：
**lendf.me正式环境**

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-76437833-5"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-76437833-5');
</script>

**test.lendf.me正式环境**

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-76437833-7"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-76437833-7');
</script>

**Comment by DreamGaoYang** [comment]
update
